name: Dev Build
run-name: "Dev build repository: ${{ github.ref_name }} #${{ github.run_number }}"
on:
  workflow_dispatch:
    inputs:
      artifact-name:
        required: false
        default: ''
        description: 'Artifact name'        
      java-version:
        required: false
        type: string
        default: "21"
        description: 'Java version (e.g., 21)'
      dry-run:
        required: false
        type: boolean
        default: false
        description: 'Dry run'

jobs:
  dev-build:
    uses: netcracker/qubership-workflow-hub/.github/workflows/maven-publish.yml@main
    with:
      maven-command: "--batch-mode package -Dgpg.skip=true -DskipTests=true"
      java-version: ${{ github.event.inputs.java-version }}
      upload-artifact: true
      artifact-id: ${{ github.event.inputs.artifact-name || github.event.repository.name }}
      server-id: "github"
    secrets:
      maven-token: ${{ secrets.GITHUB_TOKEN }}

  perform-version:
    runs-on: ubuntu-latest
    needs: dev-build
    outputs:
      metadata: "${{ steps.metadata.outputs.result }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create name
        uses: netcracker/qubership-workflow-hub/actions/metadata-action@main
        id: metadata
        with:
          configuration-path: .github/metadata-config.yml

      - name: Echo metadata
        run: echo "Metadata result ${{ steps.metadata.outputs.result }}" >> $GITHUB_STEP_SUMMARY

  docker-build:
    uses: nookyo/qubership-workflow-hub/.github/workflows/docker-publish.yml@main
    needs: perform-version
    with:
      ref: ${{ github.event.ref }}
      artifact-id: ${{ github.event.inputs.artifact-name || github.event.repository.name }}
      dry-run: ${{ inputs.dry-run }}
      download-artifact: true
      tags: '${{ needs.perform-version.outputs.metadata }}, dev'